### ISSUE TITLE
Ability to tile Terminal Area Charts with Sectional charts

### ISSUE THREAD

**Issue by jamez70** [N129BZ/chartmaker#10]
I was wondering if this was possible at zoom levels above 9 or some other values. I copied the tiles on top of the ones from Sectional and it works but they have a grey border because they aren't stitched together I assume

**Comment by N129BZ** [comment]
My chartserver app uses OpenLayers as the rendering engine and I added a menu that allows me to select charts by type. When I process the full US sectional chart and the Terminal Area charts, the app puts the TA charts as a overlay layer, so they seamlessly overlay the sectional.  I think that is pretty much exactly what you are going for... Are you using leaflet for the map rendering?

**Comment by N129BZ** [comment]
Actually, that gives me an idea... maybe I can split out the individual TA charts into separate mbtiles db's

**Comment by jamez70** [comment]
I am using leaflet. No way will I convert over to OpenLayers at this point it would be a total struggle with all the code I've written for Leaflet

**Comment by N129BZ** [comment]
Are you using mbtiles databases for leaflet, or filesystem?

**Comment by N129BZ** [comment]
Here's a Chicago terminal chart overlaying the US Sectional chart.  If this can be done in OL, there's got to be some way to do it in Leaflet...
![TerminalOverSectional](https://github.com/user-attachments/assets/f124a331-4298-4d2e-92eb-9879e74cf6ab)

**Comment by jamez70** [comment]
I figured it out

![image](https://github.com/user-attachments/assets/bfaf2ac8-8ef0-4d04-a4f4-17803a4d1168)

**Comment by jamez70** [comment]
Milwaukee has a TAC, but its not like the others. I'm not sure how they extract that one.
Here is a screenshot from vfrmap.com
![image](https://github.com/user-attachments/assets/ed6dc4c1-3ccd-4add-a6dc-7001a7c95860)

**Comment by N129BZ** [comment]
Picking out an inset off the main area chart is probably a little too challenging at the moment...  also FYI, I'm implementing the US VFR Planning Chart as # 53 in the list of individual charts.

**Comment by N129BZ** [comment]
On second thought, I could make a list of any area charts that have an inset feature on the side, and implement a new process that clips off everything but the inset...  ???

**Comment by jamez70** [comment]
I was digging around wondering how they did it. Someone must have some clipshapes already made for it

**Comment by N129BZ** [comment]
They're pretty easy to create in QGis - once you get the process down... let me know what you want and I'll make them

**Comment by N129BZ** [comment]
After too much time looking into these insets - I find they are _**not**_ geo-referenced to the main chart, plus their scaling is 1/2 of the scale of the main chart.  I think the ability to zoom on the main chart kinda makes an inset a moot point, plus I have no idea how to properly geo-reference it. When I made a shape file for the Indianapolis inset on the St Louis chart and clipped it, produced a Indianapolis.db file, it comes out on the OSM map right where it was physically on the St Louis chart.  Maybe some future release, but right now I think the proper way to handle this would be a simple PNG or WEBP of the inset and when clicking on the major airport in the main map, have the inset image pop up.

Since this issue was about overlaying terminal charts and that is working, I'm closing this issue.
